services:
  - type: web
    name: app
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
      - key: ENCRYPTION_KEY
      - key: DATABASE_URL       # linked via fromDatabase
      - key: REDIS_URL          # linked via fromService
      - key: PORT
    # If you need a disk for SQLite, use "disks:" here:
    # disks:
    #   - name: app-db
    #     mountPath: /opt/render/project/src/app/db
    #     sizeGB: 1

  - type: worker
    name: celery-worker
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: celery -A app.tasks.celery_tasks worker --loglevel=info
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
      - key: ENCRYPTION_KEY
      - key: DATABASE_URL
      - key: REDIS_URL

  - type: worker
    name: celery-beat
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: celery -A app.tasks.celery_config.celery_app beat --loglevel=info
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
      - key: ENCRYPTION_KEY
      - key: DATABASE_URL
      - key: REDIS_URL

  - type: redis
    name: fo-trading-redis
    plan: free

databases:
  - name: fo-trading-postgres
    plan: standard
